- hosts: routers
  become: true
  roles:
   - role: router

- hosts: router1
  become: true
  roles:
   - role: dhcp

- hosts: clientes
  become: true
  roles:
   - role: cliente

- hosts: all
  become: true
  roles:
   - role: common

- hosts: cliente1
  become: true
  roles:
   - role: web


